resources:
- name: koopey
  type: git
  source:
    uri: https://github.com/moleisking/koopey
    branch: master

jobs:
- name: unit
  plan:
  - get: koopey
    trigger: true
  - task: unit
    file: concourse.yml