resources:
- name: koopey
  type: git
  source:
    uri: https://github.com/moleisking/koopey
    branch: master

jobs:
- name: backend
  plan:  
  - task: build
    config:
      platform: linux
      run: 
        path: gradlew
        args:
          - bootRun

- name: frontend
  plan: 
  - task: build
     config:
      platform: linux
      run: 
        path: npm
        args:
          - start