FROM nginx:1.27
LABEL version="1.0"

COPY dist/KoopeyWebpage/ /usr/share/nginx/html
COPY docker/index.html /usr/share/nginx/html
COPY docker/nginx.conf /etc/nginx/nginx.conf

ENV KOOPEY_SERVER_HOST=192.168.1.81
ENV KOOPEY_SERVER_PORT=1709
ENV KOOPEY_SERVER_PROTOCOL=http
ENV KOOPEY_CLIENT_LANGUAGE=en
ENV GOOGLE_API_KEY=${GOOGLE_API_KEY}

EXPOSE 80
